#!/bin/bash 

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

cd $HOME 

/usr/bin/xdg-user-dirs-update

echo "Resetting kali pass" 

passwd kali  

echo "password for kali reset" 

echo "Resetting root pass" 

passwd root 

echo "password for root reset" 

echo "Changing Default ssh keys" 

mkdir /etc/ssh/backup-keys 

mv /etc/ssh/ssh_host_* /etc/ssh/backup-keys 

dpkg-reconfigure openssh-server 

md5sum /etc/ssh/ssh_host_* 

md5sum /etc/ssh/backup-keys/ssh_host_* 

read -p "Please check the md5sums above, then press any key to continue ..."  

read -t 2 -p "Installing updates and Tools" 

apt-get update 

apt install seclists 

apt install locate 

apt-get install terminator -y 

apt-get install cherrytree -y  

read -t 5 -p "Opening Visual Studio Code in a Browser" 

chown root /home/kali/.Xauthority

firefox https://code.visualstudio.com/Download#

read -p "Once you have downloaded the specific package press any key" 

cd /root/Downloads

chmod +x code_*_amd64.deb

apt install ./code_*_amd64.deb

#ohmyzsh 

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
