#!/bin/bash 

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

cd $HOME 

echo "Resetting root pass" 

passwd kali  

echo "password for kali reset" 

echo "Resetting root pass" 

passwd root 

echo "password for root reset" 

echo "Changing Default ssh keys" 

mkdir /etc/ssh/backup-keys 

mv /etc/ssh/ssh_host_* /etc/ssh/backup-keys 

dpkg-reconfigure openssh-server 

md5sum /etc/ssh/ssh_host_* 

md5sum /etc/ssh/backup-keys/ssh_host_* 

read -p "Please check the md5sums above\nPress any key to continue ..."  

read -t 2 -p "Installing updates and Tools" 

apt-get update 

apt install seclists 

apt install locate 

apt-get install terminator -y 

apt-get install cherrytree -y 

apt-get install filezilla -y  

wget https://code.visualstudio.com/download# 

cd Downloads  

sudo apt install ./code_amd64.deb 

#ohmyzsh 

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
